### ISSUE TITLE
Change randomness protocol to support instant finatlity 

### ISSUE THREAD

**Issue by barryWhiteHat** [iden3/rollup#16]
Becuase the era (~8 hours) is so long and proof generation times close 15 to 30 minutes. It makes sense to allow coordinators to give some certainty to users that their transaction will be included so they can accept it as payment for example in a paying for coffee situation. 

One way of doing this is putting the data on chain and then the users knows that either they will get paid or the coordinator will get slashed. However coordinators would prefer to wait until they ahve alot of transactions and then put them on chain. Also it may take ~ 15 seconds for this to get mined. So in the case of buying a cup of coffee this is a problem. 

In order to overcome this coordinators do the following 

1. Every time they receive a transaction they hash it with the block number they plan to include it in and then send this to the user.
2. The user now knows taht either their transaction will get mined or the coordinator will suffer a finantial loss. Because the coordinator has previously created a smart contract that holds a deposit which will be burned IF anyone can provide a message that has a transaction that was not included in that block. 

This become a problem close to the end of an epoch because the randomness for the next coordinator is now known. So there will be a window of ~ 1 proof time where no one is able to sign these transactions. 

I propose that we allow the current randomness to select this coordinator and the next one so we don't have this dead time and can always have someone who is able to give users this fast finality.

**Comment by jbaylina** [comment]
Yes, 

This is very much what we are doing.  

This is equivalent to say that the operators are already selected for the current era and for the next era.

The raffle for era i is done at the beginning of era i-1.

If the current era is e,  then the updates of the operators list (operators sign on and sign off) that are doing now,  will take effect on  era e+2.

Regarding the warrantees that an operator gives, I would let it open to the operator. And would not include in the layer 0 of the rollup. At least in the first version.

With the pattern above, any operator can write their own smart contract to do that.

The big question is how to prove that a TX is not included.   By the nonce?

Here is a possible way:

1.- User is in nonce n The user signs sends a TX for nonce n+1 to operator O that has a scheduled slot in the near future (slot s).
2.- The operator signs a receipt that says that if by the slot s+1 the nonce is not increased (e.a. The TX is not mined).  The smart contract will give some ETH.

**Comment by barryWhiteHat** [comment]
> Regarding the warrantees that an operator gives, I would let it open to the operator. And would not include in the layer 0 of the rollup. At least in the first version.

Agree. 

> The big question is how to prove that a TX is not included. By the nonce?

Its probably not good ot use the nonce because a user can have two transactiosn with the same nonce and wants to be sure that one will be batched. Since we don't store to, from , amount it seems we are limited. I suppose they could commit to a balance after the transaction was processed. But then if they include 2 transactions in a block it will fail. Let me think on this. 

There is no data stored permently just the mekle root is stored temporarily ? Have you thought about making an append only merkle tree where you store the previuos data availability roots ?
